package com.lumen.ui.screens

import androidx.compose.runtime.staticCompositionLocalOf

data class LumenStrings(
    val home: String, val servers: String, val routing: String, val settings: String, val logs: String,
    val noServer: String, val fastest: String, val addNode: String, val searchServers: String,
    val pingAll: String, val pinging: String, val importClipboard: String, val noServers: String,
    val allGroups: String, val manual: String, val subscriptions: String, val addSubscription: String,
    val refresh: String, val delete: String, val edit: String, val auto: String, val never: String,
    val nodes: String, val updated: String, val nameOptional: String, val cancel: String, val add: String,
    val splitTunneling: String, val off: String, val offDescription: String, val vpnOnly: String,
    val vpnOnlyDescription: String, val exclude: String, val excludeDescription: String,
    val appsUsingVpn: String, val appsBypassingVpn: String, val searchApps: String,
    val loadingApps: String, val hideSystem: String, val autoSelect: String, val clear: String,
    val vpnEngine: String, val connection: String, val muxDescription: String, val muxConcurrency: String,
    val tlsFragmentation: String, val tlsDescription: String, val fragmentPackets: String,
    val fragmentLength: String, val fragmentDelay: String, val tunnelMtu: String, val localProxy: String,
    val localInbound: String, val localInboundDescription: String, val allowLan: String,
    val allowLanDescription: String, val behavior: String, val autoConnect: String,
    val autoConnectDescription: String, val language: String, val systemDefault: String,
    val speedTest: String, val testing: String, val runSpeedTest: String, val export: String,
    val noLogs: String, val tapToConnect: String, val connectingStatus: String,
    val connectedStatus: String, val connectionError: String, val diagnostics: String,
    val openLogs: String, val preferIpv6: String, val preferIpv6Description: String,
    val blockQuic: String, val blockQuicDescription: String, val sniffRouteOnly: String,
    val sniffRouteOnlyDescription: String, val socksPort: String, val httpPort: String,
    val centerConnect: String, val centerConnecting: String, val centerConnected: String, val centerError: String,
    val importFromClipboard: String, val importQrCode: String, val importFromFile: String, val importManually: String,
    val refreshSubscription: String, val deleteSubscription: String, val autoUpdateOneHour: String,
    val expiresUnlimited: String, val daysRemaining: String, val serverCount: String,
    val sortByPing: String, val pingGroup: String, val sortBy: String, val sortByName: String,
    val subscriptionSettings: String, val trafficSettings: String, val appSettings: String,
    val infoSection: String, val version: String, val community: String, val back: String,
    val requestParameters: String, val directLoad: String, val directLoadDesc: String,
    val sendHwid: String, val sendHwidDesc: String, val allowOverrides: String, val allowOverridesDesc: String,
    val subscriptionProfile: String, val proxyDns: String, val directDns: String, val autoSelectUrl: String,
    val checkInterval: String, val toleranceMs: String, val appearance: String, val theme: String,
    val domainIpRouting: String, val appRouting: String, val geoResourceFiles: String,
    val domainsAndIpDirect: String, val directRulesNotice: String, val domainsDirectLabel: String,
    val ipCidrDirectLabel: String, val geoSourceLabel: String, val geoNotLoaded: String,
    val groupDefault: String, val importAction: String,
    val themeSettings: String, val done: String, val greenTheme: String, val greenThemeDesc: String,
    val lightTheme: String, val lightThemeDesc: String, val darkTheme: String, val darkThemeDesc: String,
    val additional: String, val materialYou: String, val materialYouDesc: String,
    val amoledBlack: String, val amoledBlackDesc: String, val connectionStyleTitle: String,
    val classicStyle: String, val compactStyle: String,
    val addOrPaste: String, val swipeOrTapToConnect: String, val swipeOrTapToDisconnect: String,
    val slideToConnect: String, val slideToDisconnect: String, val paste: String,
    val copyLink: String, val exportQrCode: String, val ping: String,
    val subscriptionProperties: String, val exportAll: String, val exportSelected: String,
    val selected: String, val url: String, val copied: String, val udpPing: String,
    val address: String, val action: String, val directAction: String, val proxyAction: String,
    val blockAction: String, val noRulesYet: String, val clearAll: String,
    val dnsSettings: String, val dnsModeSection: String, val dnsModeAuto: String,
    val dnsModeAndroid: String, val dnsModeSecure: String, val dnsModeJson: String,
    val dnsModeAutoHint: String, val dnsModeAndroidHint: String, val dnsModeSecureHint: String,
    val dnsModeJsonHint: String, val dnsDirectSection: String, val dnsProxySection: String,
    val dnsServersLabel: String, val dnsTypeLabel: String, val dnsStrategyLabel: String,
    val dnsIpv4Only: String, val dnsIpv4OnlyDesc: String, val dnsBehaviorSection: String,
    val dnsHijack: String, val dnsHijackDesc: String, val dnsFakeIp: String, val dnsFakeIpDesc: String,
    val dnsParallel: String, val dnsParallelDesc: String, val dnsOptimistic: String,
    val dnsOptimisticDesc: String, val dnsGeoCheck: String, val dnsGeoCheckDesc: String,
    val dnsHostsSection: String, val dnsHostsLabel: String, val dnsOverride: String,
    val dnsOverrideDesc: String, val dnsHostname: String, val dnsIpv4: String
)

private val EN = LumenStrings(
    home="Home", servers="Servers", routing="Routing", settings="Settings", logs="Logs",
    noServer="No server selected — tap to choose", fastest="fastest available", addNode="Add node",
    searchServers="Search servers…", pingAll="Ping all", pinging="Pinging…",
    importClipboard="Import clipboard", noServers="No servers yet. Add a node or subscription.",
    allGroups="All servers", manual="Manual", subscriptions="Subscriptions", addSubscription="Add subscription",
    refresh="Refresh", delete="Delete", edit="Edit", auto="Auto", never="never", nodes="nodes",
    updated="updated", nameOptional="Name (optional)", cancel="Cancel", add="Add",
    splitTunneling="Split tunneling", off="Off", offDescription="Route all traffic through the VPN",
    vpnOnly="VPN only for selected apps", vpnOnlyDescription="Only checked apps use the tunnel",
    exclude="Exclude selected apps", excludeDescription="Checked apps bypass the tunnel",
    appsUsingVpn="Apps using VPN", appsBypassingVpn="Apps bypassing VPN", searchApps="Search apps…",
    loadingApps="Loading installed apps…", hideSystem="Hide system apps", autoSelect="Auto-select",
    clear="Clear", vpnEngine="VPN engine", connection="Connection",
    muxDescription="Reuse one connection for multiple streams", muxConcurrency="MUX concurrency",
    tlsFragmentation="TLS fragmentation", tlsDescription="Split TLS ClientHello to evade DPI",
    fragmentPackets="Fragment packets", fragmentLength="Fragment length", fragmentDelay="Fragment delay (ms)",
    tunnelMtu="Tunnel MTU", localProxy="Local proxy", localInbound="Local SOCKS/HTTP inbound",
    localInboundDescription="Ports 10808 (SOCKS5) and 10809 (HTTP)", allowLan="Allow LAN connections",
    allowLanDescription="Share the local proxy on your network", behavior="Behavior",
    autoConnect="Auto-connect on boot", autoConnectDescription="Reconnect after reboot",
    language="Language", systemDefault="System default", speedTest="Speed test", testing="Testing…",
    runSpeedTest="Run speed test", export="Export", noLogs="No log entries yet.",
    tapToConnect="Tap to connect", connectingStatus="Connecting…", connectedStatus="Connected",
    connectionError="Connection error", diagnostics="Diagnostics", openLogs="Open logs",
    preferIpv6="Prefer IPv6", preferIpv6Description="Use IPv6 when IPv4 and IPv6 are both available",
    blockQuic="Block QUIC", blockQuicDescription="Reject QUIC on UDP/443 and fall back to TCP",
    sniffRouteOnly="Sniff route only", sniffRouteOnlyDescription="Use sniffing for routing without replacing destinations",
    socksPort="SOCKS port", httpPort="HTTP port",
    centerConnect="Connect", centerConnecting="Connecting…", centerConnected="Connected", centerError="Error",
    importFromClipboard="Import from clipboard", importQrCode="QR code", importFromFile="From file", importManually="Manually",
    refreshSubscription="Refresh subscription", deleteSubscription="Delete subscription",
    autoUpdateOneHour="Auto-update - 1h", expiresUnlimited="Expires: Unlimited", daysRemaining="days remaining",
    serverCount="server(s)", sortByPing="Sort by ping", pingGroup="Ping group servers",
    sortBy="Sort by:", sortByName="Name", subscriptionSettings="Subscription settings",
    trafficSettings="Traffic settings", appSettings="App settings", infoSection="INFORMATION",
    version="Version", community="Community", back="Back", requestParameters="Request parameters",
    directLoad="Load directly", directLoadDesc="Load subscription bypassing proxy",
    sendHwid="Send HWID", sendHwidDesc="Send device ID in X-Hwid header",
    allowOverrides="Allow subscription overrides", allowOverridesDesc="Apply compatible MUX, fragmentation & routing parameters",
    subscriptionProfile="Subscription profile", proxyDns="Proxy DNS", directDns="Direct DNS",
    autoSelectUrl="Check URL", checkInterval="Check interval (min)", toleranceMs="Delay tolerance (ms)",
    appearance="Appearance", theme="Theme", domainIpRouting="Domain / IP routing",
    appRouting="App routing", geoResourceFiles="Geo-resource files", domainsAndIpDirect="Direct Domains & IP",
    directRulesNotice="Specified addresses bypass proxy. Changes take effect on next connection.",
    domainsDirectLabel="Direct domains", ipCidrDirectLabel="Direct IP / CIDR",
    geoSourceLabel="Geo-resource source", geoNotLoaded="Files not downloaded yet",
    groupDefault="Default", importAction="Import",
    themeSettings="Theme", done="Done", greenTheme="Green", greenThemeDesc="Dark forest with green accent",
    lightTheme="Light", lightThemeDesc="Light mode with soft colors", darkTheme="Dark", darkThemeDesc="Clean dark with blue accent",
    additional="Additional", materialYou="Material You", materialYouDesc="Use system wallpaper colors",
    amoledBlack="AMOLED Black", amoledBlackDesc="Pure black background — saves battery on OLED",
    connectionStyleTitle="Connection style", classicStyle="Classic", compactStyle="Compact",
    addOrPaste="+ Add or Paste", swipeOrTapToConnect="Slide to Connect", swipeOrTapToDisconnect="Slide to Disconnect",
    slideToConnect="Slide to Connect", slideToDisconnect="Slide to Disconnect", paste="Paste",
    copyLink="Copy link", exportQrCode="Export QR code", ping="Ping",
    subscriptionProperties="Subscription properties", exportAll="Export all", exportSelected="Export selected",
    selected="selected", url="URL", copied="Copied", udpPing="UDP Ping",
    address="Address", action="Action", directAction="Direct", proxyAction="Proxy",
    blockAction="Block", noRulesYet="No domain or IP rules configured", clearAll="Clear all",
    dnsSettings="DNS settings", dnsModeSection="DNS mode", dnsModeAuto="Automatic",
    dnsModeAndroid="Android DNS", dnsModeSecure="Secure", dnsModeJson="From JSON",
    dnsModeAutoHint="TCP/UDP 53 is hijacked inside the VPN; direct and proxy resolvers are picked by rules.",
    dnsModeAndroidHint="System Android resolver without hijacking inside the VPN.",
    dnsModeSecureHint="DoH/DoT through the proxy outbound only; strict Private DNS is checked before start.",
    dnsModeJsonHint="DNS comes from your custom JSON config.",
    dnsDirectSection="Direct DNS", dnsProxySection="DNS over proxy",
    dnsServersLabel="Servers (one per line)", dnsTypeLabel="Type", dnsStrategyLabel="Strategy",
    dnsIpv4Only="IPv4 only over VPN", dnsIpv4OnlyDesc="Filter AAAA in the managed proxy DNS",
    dnsBehaviorSection="Behavior", dnsHijack="Hijack DNS in TUN",
    dnsHijackDesc="Do not let plain DNS queries escape the built-in resolver",
    dnsFakeIp="Fake DNS", dnsFakeIpDesc="FakeIP is off by default; enable only when needed",
    dnsParallel="Parallel queries", dnsParallelDesc="Query fallback resolvers simultaneously",
    dnsOptimistic="Optimistic cache", dnsOptimisticDesc="Serve a stale answer while refreshing in background",
    dnsGeoCheck="DNS geo check", dnsGeoCheckDesc="Keeps the direct/proxy choice for domain rules",
    dnsHostsSection="Hosts and override", dnsHostsLabel="Hosts: domain=ip",
    dnsOverride="DNS override", dnsOverrideDesc="Exact hostname → IPv4 before other DNS rules",
    dnsHostname="Hostname", dnsIpv4="IPv4"
)

private val RU = EN.copy(
    home="Главная", servers="Серверы", routing="Маршрутизация", settings="Настройки", logs="Логи",
    noServer="Сервер не выбран — нажмите, чтобы выбрать", fastest="самый быстрый", addNode="Добавить сервер",
    searchServers="Поиск серверов…", pingAll="Проверить все", pinging="Проверка…",
    importClipboard="Импорт из буфера", noServers="Серверов пока нет. Добавьте сервер или подписку.",
    allGroups="Все серверы", manual="Вручную", subscriptions="Подписки", addSubscription="Добавить подписку",
    refresh="Обновить", delete="Удалить", edit="Изменить", auto="Авто", never="никогда", nodes="серверов",
    updated="обновлено", nameOptional="Название (необязательно)", cancel="Отмена", add="Добавить",
    splitTunneling="Раздельная маршрутизация", off="Выключено", offDescription="Весь трафик через VPN",
    vpnOnly="VPN только для выбранных", vpnOnlyDescription="Только отмеченные приложения используют VPN",
    exclude="Исключить выбранные", excludeDescription="Отмеченные приложения обходят VPN",
    appsUsingVpn="Приложения через VPN", appsBypassingVpn="Приложения в обход VPN", searchApps="Поиск приложений…",
    loadingApps="Загрузка приложений…", hideSystem="Скрыть системные", autoSelect="Авто-выбор", clear="Очистить",
    vpnEngine="VPN-движок", connection="Соединение", muxDescription="Одно соединение для нескольких потоков",
    muxConcurrency="Параллельность MUX", tlsFragmentation="Фрагментация TLS",
    tlsDescription="Разделять TLS ClientHello для обхода DPI", fragmentPackets="Пакеты фрагментации",
    fragmentLength="Длина фрагмента", fragmentDelay="Задержка фрагмента (мс)", tunnelMtu="MTU туннеля",
    localProxy="Локальный прокси", localInbound="Локальный SOCKS/HTTP",
    localInboundDescription="Порты 10808 (SOCKS5) и 10809 (HTTP)", allowLan="Разрешить подключения из LAN",
    allowLanDescription="Открыть локальный прокси в сети", behavior="Поведение",
    autoConnect="Подключаться при запуске", autoConnectDescription="Переподключаться после перезагрузки",
    language="Язык", systemDefault="Как в системе", speedTest="Тест скорости", testing="Проверка…",
    runSpeedTest="Запустить тест", export="Экспорт", noLogs="Записей пока нет.",
    tapToConnect="Нажмите для подключения", connectingStatus="Подключение…",
    connectedStatus="Подключено", connectionError="Ошибка подключения",
    diagnostics="Диагностика", openLogs="Открыть логи",
    preferIpv6="Предпочитать IPv6", preferIpv6Description="Использовать IPv6, когда доступны IPv4 и IPv6",
    blockQuic="Блокировать QUIC", blockQuicDescription="Блокировать QUIC на UDP/443 с переходом на TCP",
    sniffRouteOnly="Сниффинг только для маршрутов", sniffRouteOnlyDescription="Использовать сниффинг для маршрутизации без замены адреса назначения",
    socksPort="Порт SOCKS", httpPort="Порт HTTP",
    centerConnect="Подключиться", centerConnecting="Подключение…", centerConnected="Подключено", centerError="Ошибка",
    importFromClipboard="Вставить из буфера", importQrCode="QR-код", importFromFile="Из файла", importManually="Вручную",
    refreshSubscription="Обновить подписку", deleteSubscription="Удалить подписку",
    autoUpdateOneHour="Автообновление - 1 ч.", expiresUnlimited="Истекает: Безлимитно", daysRemaining="дней осталось",
    serverCount="сервер(ов)", sortByPing="Сортировать по пингу", pingGroup="Проверить пинг группы",
    sortBy="Сортировать по:", sortByName="Имя", subscriptionSettings="Настройки подписок",
    trafficSettings="Настройки трафика", appSettings="Настройки приложения", infoSection="ИНФОРМАЦИЯ",
    version="Версия", community="Сообщество", back="Назад", requestParameters="Параметры запроса",
    directLoad="Загружать напрямую", directLoadDesc="Подписка загружается в обход выбранного прокси-сервера",
    sendHwid="Отправлять HWID", sendHwidDesc="Передавать идентификатор устройства в заголовке X-Hwid",
    allowOverrides="Разрешить настройки из подписки", allowOverridesDesc="Применять совместимые параметры MUX, фрагментации и маршрутизации",
    subscriptionProfile="Профиль подписки", proxyDns="DNS через прокси", directDns="DNS напрямую",
    autoSelectUrl="URL проверки", checkInterval="Интервал проверки (мин)", toleranceMs="Допуск задержки (мс)",
    appearance="Оформление", theme="Тема", domainIpRouting="Маршрутизация по домену/IP",
    appRouting="Маршрутизация приложений", geoResourceFiles="Файлы георесурсов", domainsAndIpDirect="Домены и IP напрямую",
    directRulesNotice="Указанные адреса обходят прокси. Изменения применятся при следующем подключении.",
    domainsDirectLabel="Домены напрямую", ipCidrDirectLabel="IP / CIDR напрямую",
    geoSourceLabel="Источник георесурсов", geoNotLoaded="Файлы ещё не загружены",
    groupDefault="Default", importAction="Импорт",
    themeSettings="Тема", done="Готово", greenTheme="Зелёная", greenThemeDesc="Тёмный лес с зелёным акцентом",
    lightTheme="Светлая", lightThemeDesc="Светлый режим с мягкими цветами", darkTheme="Тёмная", darkThemeDesc="Чистый тёмный с голубым акцентом",
    additional="Дополнительно", materialYou="Material You", materialYouDesc="Использовать цвета обоев системы",
    amoledBlack="AMOLED чёрный", amoledBlackDesc="Чистый чёрный фон — экономит заряд на OLED",
    connectionStyleTitle="Стиль подключения", classicStyle="Классический", compactStyle="Компактный",
    addOrPaste="+ Добавить или Вставить", swipeOrTapToConnect="Проведите для подключения", swipeOrTapToDisconnect="Проведите для отключения",
    slideToConnect="Проведите для подключения", slideToDisconnect="Проведите для отключения", paste="Вставить",
    copyLink="Копировать ссылку", exportQrCode="Экспорт в QR-код", ping="Пинг",
    subscriptionProperties="Свойства подписки", exportAll="Экспорт всех", exportSelected="Экспорт выбранных",
    selected="выбрано", url="URL", copied="Скопировано", udpPing="UDP Пинг",
    address="Адрес", action="Действие", directAction="Прямой", proxyAction="Прокси",
    blockAction="Блокировать", noRulesYet="Правила по доменам и IP не заданы", clearAll="Очистить все",
    dnsSettings="Настройки DNS", dnsModeSection="Режим DNS", dnsModeAuto="Автоматически",
    dnsModeAndroid="DNS Android", dnsModeSecure="Защищённый", dnsModeJson="Из JSON",
    dnsModeAutoHint="TCP/UDP 53 перехватывается внутри VPN, прямые и proxy resolver подбираются по правилам.",
    dnsModeAndroidHint="Системный resolver Android без перехвата внутри VPN.",
    dnsModeSecureHint="DoH/DoT только через proxy outbound; строгий Private DNS проверяется до старта.",
    dnsModeJsonHint="DNS берётся из пользовательского JSON-конфига.",
    dnsDirectSection="Прямой DNS", dnsProxySection="DNS через прокси",
    dnsServersLabel="Серверы (по одному в строке)", dnsTypeLabel="Тип", dnsStrategyLabel="Стратегия",
    dnsIpv4Only="Только IPv4 через VPN", dnsIpv4OnlyDesc="Фильтровать AAAA в управляемом proxy DNS",
    dnsBehaviorSection="Поведение", dnsHijack="Перехватывать DNS в TUN",
    dnsHijackDesc="Не выпускать обычные DNS-запросы мимо встроенного resolver",
    dnsFakeIp="Fake DNS", dnsFakeIpDesc="FakeIP выключен по умолчанию; включайте только при необходимости",
    dnsParallel="Параллельные запросы", dnsParallelDesc="Опрашивать резервные resolver одновременно",
    dnsOptimistic="Оптимистичный кэш", dnsOptimisticDesc="Разрешить устаревший ответ с обновлением в фоне",
    dnsGeoCheck="Geo-проверка DNS", dnsGeoCheckDesc="Сохраняет прямой/proxy выбор для доменных правил",
    dnsHostsSection="Hosts и override", dnsHostsLabel="Hosts: domain=ip",
    dnsOverride="DNS override", dnsOverrideDesc="Точный hostname → IPv4 до остальных DNS-правил",
    dnsHostname="Hostname", dnsIpv4="IPv4"
)

private val ZH = EN.copy(
    home="主页", servers="服务器", routing="路由", settings="设置", logs="日志",
    subscriptions="订阅", addSubscription="添加订阅", searchServers="搜索服务器…",
    hideSystem="隐藏系统应用", autoSelect="自动选择", clear="清除",
    language="语言", systemDefault="跟随系统", speedTest="速度测试", runSpeedTest="开始测试",
    tapToConnect="点击连接", connectingStatus="正在连接…", connectedStatus="已连接",
    connectionError="连接错误", diagnostics="诊断", openLogs="打开日志",
    preferIpv6="优先使用 IPv6", preferIpv6Description="IPv4 和 IPv6 都可用时优先使用 IPv6",
    blockQuic="阻止 QUIC", blockQuicDescription="阻止 UDP/443 上的 QUIC 并回退到 TCP",
    sniffRouteOnly="仅用于路由嗅探", sniffRouteOnlyDescription="嗅探仅用于路由，不替换目标地址",
    socksPort="SOCKS 端口", httpPort="HTTP 端口",
    centerConnect="连接", centerConnecting="正在连接…", centerConnected="已连接", centerError="错误",
    importFromClipboard="剪贴板导入", importQrCode="二维码", importFromFile="从文件导入", importManually="手动添加",
    refreshSubscription="刷新订阅", deleteSubscription="删除订阅",
    autoUpdateOneHour="自动更新 - 1小时", expiresUnlimited="到期时间: 无限制", daysRemaining="天剩余",
    serverCount="个服务器", sortByPing="按延迟排序", pingGroup="测试分组延迟",
    sortBy="排序方式:", sortByName="名称", subscriptionSettings="订阅设置",
    trafficSettings="流量设置", appSettings="应用设置", infoSection="信息",
    version="版本", community="社区", back="返回", requestParameters="请求参数",
    directLoad="直接加载", directLoadDesc="绕过代理加载订阅",
    sendHwid="发送 HWID", sendHwidDesc="在 X-Hwid 标头中发送设备 ID",
    allowOverrides="允许订阅覆盖", allowOverridesDesc="应用兼容的 MUX、分片和路由参数",
    subscriptionProfile="订阅配置", proxyDns="代理 DNS", directDns="直连 DNS",
    autoSelectUrl="检查 URL", checkInterval="检查间隔 (分钟)", toleranceMs="延迟容忍度 (毫秒)",
    appearance="外观", theme="主题", domainIpRouting="域名 / IP 路由",
    appRouting="应用路由", geoResourceFiles="Geo 资源文件", domainsAndIpDirect="直连域名与 IP",
    directRulesNotice="指定的地址将绕过代理。更改将在下次连接时生效。",
    domainsDirectLabel="直连域名", ipCidrDirectLabel="直连 IP / CIDR",
    geoSourceLabel="Geo 资源来源", geoNotLoaded="文件尚未下载",
    groupDefault="默认", importAction="导入",
    themeSettings="主题", done="完成", greenTheme="绿色", greenThemeDesc="带绿色点缀的深色森林",
    lightTheme="浅色", lightThemeDesc="柔和色彩的浅色模式", darkTheme="深色", darkThemeDesc="带蓝色点缀的纯正深色",
    additional="附加设置", materialYou="Material You", materialYouDesc="使用系统壁纸颜色",
    amoledBlack="AMOLED 纯黑", amoledBlackDesc="纯黑背景 — 在 OLED 上更省电",
    connectionStyleTitle="连接样式", classicStyle="经典", compactStyle="紧凑"
)

private val FA = EN.copy(
    home="خانه", servers="سرورها", routing="مسیریابی", settings="تنظیمات", logs="گزارش‌ها",
    subscriptions="اشتراک‌ها", addSubscription="افزودن اشتراک", hideSystem="پنهان کردن برنامه‌های سیستمی",
    autoSelect="انتخاب خودکار", clear="پاک کردن", language="زبان", systemDefault="پیش‌فرض سیستم",
    tapToConnect="برای اتصال ضربه بزنید", connectingStatus="در حال اتصال…",
    connectedStatus="متصل", connectionError="خطای اتصال", diagnostics="عیب‌یابی",
    openLogs="باز کردن گزارش‌ها", preferIpv6="ترجیح IPv6",
    preferIpv6Description="وقتی IPv4 و IPv6 در دسترس هستند از IPv6 استفاده شود",
    blockQuic="مسدود کردن QUIC", blockQuicDescription="QUIC روی UDP/443 مسدود و از TCP استفاده شود",
    sniffRouteOnly="اسنیف فقط برای مسیریابی", sniffRouteOnlyDescription="اسنیف فقط برای مسیریابی باشد и مقصد را تغییر ندهد",
    socksPort="پورت SOCKS", httpPort="پورت HTTP",
    centerConnect="اتصال", centerConnecting="در حال اتصال…", centerConnected="متصل شد", centerError="خطا",
    importFromClipboard="جای‌گذاری از حافظه", importQrCode="کد QR", importFromFile="از فایل", importManually="دستی",
    refreshSubscription="به‌روزرسانی اشتراک", deleteSubscription="حذف اشتراک",
    autoUpdateOneHour="به‌روزرسانی خودکار - ۱ ساعت", expiresUnlimited="انقضا: نامحدود", daysRemaining="روز باقی‌مانده",
    serverCount="سرور", sortByPing="مرتب‌سازی بر اساس پینگ", pingGroup="تست پینگ گروه",
    sortBy="مرتب‌سازی بر اساس:", sortByName="نام", subscriptionSettings="تنظیمات اشتراک",
    trafficSettings="تنظیمات ترافیک", appSettings="تنظیمات برنامه", infoSection="اطلاعات",
    version="نسخه", community="انجمن", back="بازگشت", requestParameters="پارامترهای درخواست",
    directLoad="بارگیری مستقیم", directLoadDesc="بارگیری اشتراک بدون استفاده از پروکسی",
    sendHwid="ارسال HWID", sendHwidDesc="ارسال شناسه دستگاه در هدر X-Hwid",
    allowOverrides="اجازه اعمال تنظیمات اشتراک", allowOverridesDesc="اعمال تنظیمات سازگار MUX، تکه‌تکه‌سازی и مسیریابی",
    subscriptionProfile="پروفایل اشتراک", proxyDns="دی‌ان‌اس پروکسی", directDns="دی‌ان‌اس مستقیم",
    autoSelectUrl="آدرس بررسی", checkInterval="فاصله بررسی (دقیقه)", toleranceMs="تحمل تاخیر (میلی‌ثانیه)",
    appearance="ظاهر", theme="پوسته", domainIpRouting="مسیریابی دامنه / IP",
    appRouting="مسیریابی برنامه‌ها", geoResourceFiles="فایل‌های منابع جغرافیا", domainsAndIpDirect="دامنه‌ها и IPهای مستقیم",
    directRulesNotice="آدرس‌های مشخص شده پروکسی را دور می‌زنند. تغییرات در اتصال بعدی اعمال می‌شوند.",
    domainsDirectLabel="دامنه‌های مستقیم", ipCidrDirectLabel="IP / CIDR مستقیم",
    geoSourceLabel="منبع اطلاعات جغرافیایی", geoNotLoaded="فایل‌ها هنوز دانلود نشده‌اند",
    groupDefault="پیش‌فرض", importAction="وارد کردن",
    themeSettings="پوسته", done="انجام شد", greenTheme="سبز", greenThemeDesc="جنگل تاریک با رنگ سبز",
    lightTheme="روشن", lightThemeDesc="حالت روشن با رنگ‌های ملایم", darkTheme="تاریک", darkThemeDesc="تاریک خالص با رنگ آبی",
    additional="اضافی", materialYou="Material You", materialYouDesc="استفاده از رنگ‌های تصویر زمینه سیستم",
    amoledBlack="مشکی AMOLED", amoledBlackDesc="پس‌زمینه کاملاً مشکی — کاهش مصرف باتری در OLED",
    connectionStyleTitle="سبک اتصال", classicStyle="کلاسیک", compactStyle="فشرده"
)

val LocalStrings = staticCompositionLocalOf { EN }

fun stringsForLanguage(code: String): LumenStrings = when (code.lowercase()) {
    "ru" -> RU
    "zh" -> ZH
    "fa" -> FA
    else -> EN
}
